name: Deploy Laravel Application

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: List files for debugging
      run: ls -la
      shell: bash

    - name: Setup FTP deployment
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ftp.upseba.com.bd
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: ${{secrets.FTP_SERVER }}


# Ensure you add the following secrets in your GitHub repository:
# FTP_USERNAME: lms.upseba.com.bd@lms.upseba.com.bd
# FTP_PASSWORD: Monaem66@@
